FROM alpine:3
ENV BASE_URL=localhost
RUN set -x \
 && echo http://dl-cdn.alpinelinux.org/alpine/edge/testing/ >> /etc/apk/repositories \
 && apk add --update --no-cache zola
WORKDIR /var/www

EXPOSE 1111
EXPOSE 1000

CMD /usr/bin/zola serve --drafts --interface=0.0.0.0 --base-url=${BASE_URL}
